services:
  - type: web
    name: viajaufsc-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeployTrigger: off
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: VIAJAUFSC_CORS_ORIGINS
        sync: false
